### ISSUE TITLE
请问这个

### ISSUE THREAD

**Issue by hqc158754** [xaboy/form-create-designer#1]
请问这个表单设计器后续会出基于ant-design-vue  版本的开发吗，今年上半年会出吗？

**Comment by hqc158754** [comment]
Will this form designer be developed based on the ant-design-vue version? Will it be released in the first half of this year?

**Comment by xaboy** [comment]
不好意思, 目前还没有计划. 目前计划是先维护和丰富`element-ui`版本的功能 @hqc158754

**Comment by xiaolannuoyi** [comment]
会出vue3的版本么， element-plus 的

**Comment by xaboy** [comment]
vue3版本会出

**Comment by leotian** [comment]
支持 iview/view design 吗，有支持计划吗

**Comment by lianghongle** [comment]
> vue3版本会出

请问，vue3的，有计划是什么时候能出来吗？
