### ISSUE TITLE
TableOptions组件问题

### ISSUE THREAD

**Issue by Dawnsc** [xaboy/form-create-designer#104]
路径: form-create-designer/src/components/TableOptions.vue

问题描述: 在designer页面操作时, 输入静态数据, 再删除, 因onInput方法, 校验判断非空字符串等场景, 导致保存后, 删除操作未生效.

源码: 
onInput(item) {
  if (item.label && item.value) {
      this.input();
  }
},

修复:
onInput(item) {
  if (item.label != undefined && item.value != undefined) {
      this.input();
  }
},

**Comment by xaboy** [comment]
已修复
