### ISSUE TITLE
vue3 版本在清空rule后重新加入元素 第二个元素会无法加入，这是为什么？

### ISSUE THREAD

**Issue by zl1310362** [xaboy/form-create-designer#107]
<img width="1383" alt="image" src="https://github.com/xaboy/form-create-designer/assets/42571754/083e828a-1dc5-4a5b-9ed2-c3759558bc50">

**Comment by coolwhg** [comment]
相同的问题，调用setRule操作后都不能在拖入第二个元素，也不能删除元素和编辑元素！浏览器无响应，console无报错

**Comment by xaboy** [comment]
form-create更新到3.1.27修复
