### ISSUE TITLE
关于创建group拖拽组件

### ISSUE THREAD

**Issue by chengpeng666** [xaboy/form-create-designer#11]
想在左侧的组件列表中添加group的组件按钮，但是group.js不知道怎么写。

const label = '数组组件';
const name = 'group';
export default {
    icon: 'icon-group',
    label,
    name,
    drag: true,
    dragBtn: true,
    rule() {
        return {
            field: uniqueId(),
            title: label,
            type: 'group',
            props:{
                rules: []
            }
        };
    },
    props() {
        return [];
    }
};
`
这样写没有办法向group里拖入其他组件。

**Comment by xaboy** [comment]
拖拽目前还不支持 group 组件
