### ISSUE TITLE
fc-designer 组件 接口数据/解析函数 无法设置

### ISSUE THREAD

**Issue by cyberkingkong** [xaboy/form-create-designer#110]
fc-designer 组件 接口数据/解析函数 
例:
创建 select 组件，并设置数据为接口数据，设置接口地址，并设置解析函数，提交后 fetch的parse是空的。
看了以前老版本是 _parse，后面改成了 parse ，并删减了很多代码，不知道是不是这里的原因。

**Comment by xaboy** [comment]
需要通过`$refs.fd.getJson()`方法获取json规则,使用时通过`formCreate.parseJson`方法解析

**Comment by rujianwang** [comment]
接口地址是动态设置参数的 要怎么设置

**Comment by xaboy** [comment]
最新版本中已经优化
