### ISSUE TITLE
怎么自定义组件的规则？

### ISSUE THREAD

**Issue by NJHSFNAK** [xaboy/form-create-designer#114]
大佬，请问怎么自定义组件规则，我使用**addComponent**生成了自定义组件，且在组件配置栏中看到了自定义的规则，但在组件回显时就自定义的规则就不显示了，请问大佬我应该怎么修改。
<img width="1259" alt="image" src="https://github.com/xaboy/form-create-designer/assets/38530519/3052171a-33e1-4246-812d-3793daf39f7f">
<img width="1726" alt="image" src="https://github.com/xaboy/form-create-designer/assets/38530519/041c7ec5-ac6a-4120-baa5-57bb582816e4">
@xaboy

**Comment by xaboy** [comment]
回显的时候没有重新执行自定义规则的操作?

**Comment by NJHSFNAK** [comment]
> 回显的时候没有重新执行自定义规则的操作?

作者您好，有调用**setRule**方法，如果不对的话，请大佬给个方向我好修改下

**Comment by xaboy** [comment]
右侧的选项消失了,首先得检查自定义组件挂载的时机,可能是某些情况下没有执行 @NJHSFNAK
