### ISSUE TITLE
编辑器组件没有虚线边框什么原因

### ISSUE THREAD

**Issue by yangxiaosysu** [xaboy/form-create-designer#115]
<img width="737" alt="微信图片_20240111202808" src="https://github.com/xaboy/form-create-designer/assets/78070340/1ebec51b-ee90-4b12-b234-8785b3d9ba26">

**Comment by xaboy** [comment]
那个版本?有没有改动过代码?

**Comment by yangxiaosysu** [comment]
最新的版本没有改动过代码 直接node集成进来的
<img width="517" alt="微信图片_20240115090715" src="https://github.com/xaboy/form-create-designer/assets/78070340/58080a67-7ec0-4998-b040-c22bec87938b">
<img width="313" alt="微信图片_20240115090800" src="https://github.com/xaboy/form-create-designer/assets/78070340/298cf2b3-59f9-40dc-a17c-31e3425ac248">

**Comment by yangxiaosysu** [comment]
{"form":{"labelPosition":"right","size":"small","labelWidth":"125px","hideRequiredAsterisk":false,"showMessage":true,"inlineMessage":false},"submitBtn":{"show":true,"innerText":"提交"},"resetBtn":{"show":false,"innerText":"重置"}}

["{\"type\":\"input\",\"field\":\"Fuqc61m1vu4hj\",\"title\":\"输入框\",\"info\":\"\",\"$required\":false,\"_fc_drag_tag\":\"input\",\"hidden\":false,\"display\":true}","{\"type\":\"input\",\"field\":\"Fs8061m1vub2a\",\"title\":\"输入框\",\"info\":\"\",\"$required\":false,\"_fc_drag_tag\":\"input\",\"hidden\":false,\"display\":true}","{\"type\":\"inputNumber\",\"field\":\"Foqm61m1vuicl\",\"title\":\"计数器\",\"info\":\"\",\"$required\":false,\"_fc_drag_tag\":\"inputNumber\",\"hidden\":false,\"display\":true}"]

**Comment by xaboy** [comment]
没有复现

<img width="1079" alt="image" src="https://github.com/xaboy/form-create-designer/assets/21242408/98620985-effa-4533-ab06-14dd705cb03a">

**Comment by xaboy** [comment]
开源代码运行起来测试的,演示站(https://form-create.com/v3/designer)测试也是正常

**Comment by yangxiaosysu** [comment]
好的 谢谢

**Comment by a847244052** [comment]
是不是有 outline: none !important 类似的
