### ISSUE TITLE
您好 我想咨询一下form-create-designer的问题

### ISSUE THREAD

**Issue by csj999999** [xaboy/form-create-designer#116]
您好， 很抱歉打扰了，我最近用[form-create-designer](https://github.com/xaboy/form-create-designer)，引进了我的vue3项目中，正常创建还是正常的，如果保存之后再拿到数据展示出来，就不能拖动和删除，也不能继续拖动增加组件，vue3版本有这个问题，vue2是完全正常的，希望您抽空可以帮一下忙，谢谢

**Comment by xaboy** [comment]
之前版本中有bug,将设计器和form-create更新到最新版本就正常了 @csj999999
