### ISSUE TITLE
您好 想咨询一下@form-create/designer的问题

### ISSUE THREAD

**Issue by csj999999** [xaboy/form-create-designer#119]
您好，打扰了，动态表单目前移动端只能支持TDesign这个框架吗？目前您还有其他移动端的开发计划嘛，如果我想用Taro,这个可以直接支持吗？希望您可以给一下建议，谢谢了，麻烦了

**Comment by rujianwang** [comment]
参考form-create源码自己适配 我也在搞这个，不过不是Taro
