### ISSUE TITLE
请问下你的master分支的 node版本是多少

### ISSUE THREAD

**Issue by rujianwang** [xaboy/form-create-designer#122]

**Comment by xaboy** [comment]
我本地用的是v14.21.3

**Comment by rujianwang** [comment]
@xaboy 还想请教一下，  "scripts": {
    "clean": "rimraf dist/",
    "bili": "cross-env bili",
    "build": "npm-run-all clean bili"
  }, 这里的bili是啥意思

**Comment by rujianwang** [comment]
问题已解决
