### ISSUE TITLE
仅仅拖拽两个按钮，设计界面与预览界面样式出现偏差

### ISSUE THREAD

**Issue by eloves** [xaboy/form-create-designer#130]
拖拽两个按钮进入画布，画布上展示的两个块级元素的按钮，预览界面展示的是同一行内的两个行内元素。需要支持下行内元素在画布中的展示。
![image](https://github.com/xaboy/form-create-designer/assets/26184536/0a43e10a-7d37-43d5-9210-4e510ce39038)

**Comment by xaboy** [comment]
需要用栅格组件包一下
