### ISSUE TITLE
表单组件自定义on事件，粗糙实现了，请大佬指点

### ISSUE THREAD

**Issue by simpleKeeper2022** [xaboy/form-create-designer#135]
![71b4bf1bf8ca9ef854c2e0ca44688cb](https://github.com/xaboy/form-create-designer/assets/111417388/1acb084a-d9d1-4ae9-89a8-1358a3645c50)
![f1f4d75bfca7b83a11ac1c24b13584a](https://github.com/xaboy/form-create-designer/assets/111417388/16ffdeda-4703-48f8-8217-c6fa027d8128)
![e36d6f6ae58a613aa61a791cf5ab73e](https://github.com/xaboy/form-create-designer/assets/111417388/18f5ee44-c638-4b16-af0f-cf6ad130c275)
我想提个pr，希望大佬指点下

**Comment by xaboy** [comment]
感谢支持,可以提交上来,我看一下

**Comment by xaboy** [comment]
最新版本已经支持
