### ISSUE TITLE
回显报错,后端开发看到这一串东西报错，表示有压力，以下代码是按照新手教程操作的

### ISSUE THREAD

**Issue by mynameiscuining** [xaboy/form-create-designer#145]
![image](https://github.com/xaboy/form-create-designer/assets/16378568/497e66d6-600f-414b-afef-331a68d6eaaa)
![image](https://github.com/xaboy/form-create-designer/assets/16378568/6babbb21-0f24-4493-b5d8-bf544cbc39c9)
![image](https://github.com/xaboy/form-create-designer/assets/16378568/d94f981b-6183-45aa-bd75-5bb6ad1e6dc6)
![image](https://github.com/xaboy/form-create-designer/assets/16378568/9408a611-7690-408c-aedc-e82f33e8d89e)
![image](https://github.com/xaboy/form-create-designer/assets/16378568/ec947ebb-5ab8-481b-80b5-ea916071ec4a)
数据格式 
rule：[{"type":"fcRow","children":[{"type":"col","props":{"span":12},"children":[{"type":"cascader","field":"Fplglx7f2u21bvc","title":"级联选择器","info":"","effect":{"fetch":""},"$required":false,"props":{"options":[{"label":"选项200","value":1,"children":[{"label":"选项100","value":2,"children":[{"label":"选项00","value":3},{"label":"选项01","value":4},{"label":"选项02","value":5}]},{"label":"选项101","value":6,"children":[{"label":"选项00","value":7},{"label":"选项01","value":8},{"label":"选项02","value":9}]},{"label":"选项102","value":10,"children":[{"label":"选项00","value":11},{"label":"选项01","value":12},{"label":"选项02","value":13}]}]},{"label":"选项201","value":14,"children":[{"label":"选项100","value":15,"children":[{"label":"选项00","value":16},{"label":"选项01","value":17},{"label":"选项02","value":18}]},{"label":"选项101","value":19,"children":[{"label":"选项00","value":20},{"label":"选项01","value":21},{"label":"选项02","value":22}]},{"label":"选项102","value":23,"children":[{"label":"选项00","value":24},{"label":"选项01","value":25},{"label":"选项02","value":26}]}]},{"label":"选项202","value":27,"children":[{"label":"选项100","value":28,"children":[{"label":"选项00","value":29},{"label":"选项01","value":30},{"label":"选项02","value":31}]},{"label":"选项101","value":32,"children":[{"label":"选项00","value":33},{"label":"选项01","value":34},{"label":"选项02","value":35}]},{"label":"选项102","value":36,"children":[{"label":"选项00","value":37},{"label":"选项01","value":38},{"label":"选项02","value":39}]}]}]},"_fc_id":"id_Fey8lx7f2u22bwc","name":"ref_Faq1lx7f2u22bxc","display":true,"hidden":false,"_fc_drag_tag":"cascader"}],"_fc_id":"id_F35ylx7f2ra1brc","name":"ref_Fooolx7f2ra1bsc","display":true,"hidden":false,"_fc_drag_tag":"col"},{"type":"col","props":{"span":12},"children":[{"type":"input","field":"Fsillx7f2zx5byc","title":"输入框","info":"","$required":false,"_fc_id":"id_F3xblx7f2zx5bzc","name":"ref_Fp4plx7f2zx5c0c","display":true,"hidden":false,"_fc_drag_tag":"input"}],"_fc_id":"id_Faj4lx7f2ra1btc","name":"ref_Fdiclx7f2ra1buc","display":true,"hidden":false,"_fc_drag_tag":"col"}],"_fc_id":"id_Faxflx7f2ra1bpc","name":"ref_Ftholx7f2ra1bqc","display":true,"hidden":false,"_fc_drag_tag":"fcRow"},{"type":"div","wrap":{"show":false},"native":true,"style":{"width":"100%","height":"20px"},"_fc_id":"id_Fwbvlx7g34icabc","name":"ref_F4hdlx7g34icacc","display":true,"hidden":false,"_fc_drag_tag":"space"}]
option:  {"form":{"inline":false,"hideRequiredAsterisk":false,"labelPosition":"right","size":"default","labelWidth":"125px"},"resetBtn":{"show":false,"innerText":"重置"},"submitBtn":{"show":true,"innerText":"提交"},"formName":"测试表单"}

**Comment by mynameiscuining** [comment]
![image](https://github.com/xaboy/form-create-designer/assets/16378568/a9a5da0b-d58a-4212-bc2c-7419964af6e5)
![image](https://github.com/xaboy/form-create-designer/assets/16378568/01212316-a6b2-4640-a94b-5535568ea59e)

**Comment by xaboy** [comment]
@mynameiscuining  formCreate没有正常挂载 https://form-create.com/v3/guide/mount
```vue
<template>
    <FormCreate :rule="rule"></FormCreate>
</template>
<script setup>
//导入 form-create
import formCreate from "@form-create/element-ui";
//获取 formCreate 组件
const FormCreate = formCreate.$form();
</script>
```
