### ISSUE TITLE
复制上传组件报错Invalid prop: type check failed for prop "action". Expected String, got Undefined

### ISSUE THREAD

**Issue by NorthWind17** [xaboy/form-create-designer#148]
form-create/designer": "^1.1.2
"element-ui": "^2.15.6"
"vue": "^2.7.14"
在复制上传组件的时候报错，其他组件正常，虽然报错了但是复制是正常进行的，我在官网试了下没有action的时候是可以复制
![WechatIMG16 1](https://github.com/xaboy/form-create-designer/assets/27992752/7450fd58-7091-427b-8b67-89ce06de8432)

**Comment by xaboy** [comment]
感谢反馈, 下个版本修复
