### ISSUE TITLE
本地项目为Vue3ant design vue和viteTS。集成form-create-designer后画面中表单设计器显示失败

### ISSUE THREAD

**Issue by sqw-max** [xaboy/form-create-designer#153]
我使用的是formcreate的V3和ant design vue版本。
"@form-create/ant-design-vue": "^3.2.1",
    "@form-create/designer": "^3.2.3",
   "ant-design-vue": "^4.1.2",
    "vue": "^3.4.19",
    
    import formCreate from '@form-create/ant-design-vue'
import FcDesigner from '@form-create/designer';
app.use(FcDesigner)
  app.use(formCreate)
   <fc-designer ref="designer" height="100vh" />
   
   结果：画面中的设计器样式不完整，使用不了

**Comment by sqw-max** [comment]
![Uploading Snipaste_2024-07-23_15-12-12.png…]()

**Comment by xaboy** [comment]
图片没有显示, 估计是element-plus样式没有导入.  设计器目前只有element-plus版本的
