### ISSUE TITLE
校验问题

### ISSUE THREAD

**Issue by cv-msan** [xaboy/form-create-designer#154]
请问什么时候可以支持联动校验

**Comment by xaboy** [comment]
联动校验是什么功能

**Comment by cv-msan** [comment]
就是比如，有两个输入框，a输入框输入什么内容的时候b输入框必填否则不必填，或者说a输入框输入什么内容的时候显示b输入框类似于这种的

**Comment by xaboy** [comment]
这个功能目前高级版有, 开源版没有 @cv-msan
