### ISSUE TITLE
showTemplate无效

### ISSUE THREAD

**Issue by 1548583993** [xaboy/form-create-designer#155]
请问开源版没有“模板”及相关功能么？designer v3.2.3，初始没有“模板”分组，showTemplate改true也无效。

**Comment by xaboy** [comment]
模板是pro版本的功能

**Comment by 1548583993** [comment]
谢。再请问，是否可以隐藏功能模块中的某一个配置项？例如想隐藏“属性配置”中的“最小输入长度”？
![image](https://github.com/user-attachments/assets/13d2d099-dc9d-4336-9047-7093b2bd7a46)

**Comment by xaboy** [comment]
下个版本支持

**Comment by xaboy** [comment]
最新版本已支持
