### ISSUE TITLE
vue2打包发到线上报错 Uncaught  TypeError: Object(...) is not a function

### ISSUE THREAD

**Issue by NorthWind17** [xaboy/form-create-designer#156]
"vue": "^2.7.14",
"@form-create/ant-design-vue": "^2.5.35",
    "@form-create/data": "^2.5.0-alpha.1",
    "@form-create/designer": "^1.1.3",
    "@form-create/utils": "^2.5.35",
本地运行正常，build后发到线上报错chunk-vendors.9264c428.js:64 Uncaught  TypeError: Object(...) is not a function
我用http-server启动本地dist的包，也是报该错
var yo = bo.exports;
            const wo = go(yo)
              , ko = wo
              , Co = wo.factory();
            let _o = null
              , xo = Object(i["ref"])(null);   ref是undefined

**Comment by YZSPSJK** [comment]
@NorthWind17  您好， 请问是如何解决的？
