### ISSUE TITLE
将组件拖到对象和数组

### ISSUE THREAD

**Issue by chengpeng666** [xaboy/form-create-designer#159]
<img width="853" alt="Snipaste_2024-08-17_10-26-02" src="https://github.com/user-attachments/assets/2d563f71-bc2d-451f-a228-c74a6861b574">

![Snipaste_2024-08-17_10-29-49](https://github.com/user-attachments/assets/4b40d08b-7e33-43cf-b6a0-3f295a1cd289)

Vue2版本，将画布中的一个组件拖入到数组、对象、栅格等组件时，控制台报错，该报错会导致拖入失败，虽然画布上显示能拖入，但是实际预览并没有拖入成功。

**Comment by chengpeng666** [comment]
还请修复在，感谢

**Comment by chengpeng666** [comment]
还请修复下，谢谢

**Comment by xaboy** [comment]
下个版本修复, 明天发布

**Comment by xaboy** [comment]
最新版本已修复
