### ISSUE TITLE
验证规则选择自定义时和线上的DEMO不一致

### ISSUE THREAD

**Issue by dengliyan** [xaboy/form-create-designer#161]
从线上拉下来的代码，在本地运行，选择自定义规则时整个验证规则表单消失了，只有一个+号的图标，选择其他的正常
![A](https://github.com/user-attachments/assets/c0dbfb90-60a9-4d22-baae-e7d6ce033e55)
![b](https://github.com/user-attachments/assets/a89373cf-3172-41b0-a9a7-21ecf57e9795)

**Comment by xaboy** [comment]
下个版本修复

**Comment by xaboy** [comment]
最新版本已修复
