### ISSUE TITLE
项目中，将"@form-create/designer"从“3.1.3”升到"3.2.6"后，fcDesigner拖出组件到中心区域，所有在此区域的组件都变成选中状态，无法对单个组件进行组件配置了。

### ISSUE THREAD

**Issue by SheffyYu** [xaboy/form-create-designer#165]
项目中，将"@form-create/designer"从“3.1.3”升到"3.2.6"后，fcDesigner拖出组件到中心区域，所有在此区域的组件都变成选中状态，无法对单个组件进行组件配置了。

**Comment by xaboy** [comment]
`@form-create/element-ui`更新到最新版本 @SheffyYu
