### ISSUE TITLE
@form-create/iview4

### ISSUE THREAD

**Issue by myGitHub-003** [xaboy/form-create-designer#167]
// import formCreate from '@form-create/element-ui';
import formCreate from '@form-create/iview4';

const viewForm = formCreate;

const designerForm = formCreate.factory();
console.log(formCreate, 'formCreate')
export default viewForm;

export {designerForm};
编辑器替换成iview渲染，拖拽就不好使了呢

**Comment by myGitHub-003** [comment]
vue2版本

**Comment by xaboy** [comment]
设计器不支持iview
