### ISSUE TITLE
codemirror 版本问题

### ISSUE THREAD

**Issue by Hazel-Lin** [xaboy/form-create-designer#177]
"codemirror": "^6.65.7", 

定义的 codemirror 版本并未找到，为什么指定该版本呢

**Comment by xaboy** [comment]
<img width="867" alt="image" src="https://github.com/user-attachments/assets/b6b14c67-2b92-4e6d-abf3-c76532e9aa18">
<img width="808" alt="image" src="https://github.com/user-attachments/assets/f86e5344-efc0-47e2-9e07-b9fe13a48a71">

为什么
