### ISSUE TITLE
谷歌最新版浏览器网页崩溃

### ISSUE THREAD

**Issue by guo-ico** [xaboy/form-create-designer#179]
谷歌mac最新版浏览器点击高级配置下的隐藏条件等弹框中的确定按钮，网页崩溃

**Comment by guo-ico** [comment]
Chrome 已是最新版本
版本 131.0.6778.205（正式版本） (arm64)

**Comment by xaboy** [comment]
感谢反馈, 我这边复现一下试试 @guo-ico

**Comment by xaboy** [comment]
这边没有复现
