### ISSUE TITLE
怎么在页面中做组件的层级联动

### ISSUE THREAD

**Issue by zhoulianzhi2014** [xaboy/form-create-designer#2]

**Comment by xaboy** [comment]
designer 目前还不支持组件直接的联动

**Comment by labro** [comment]
> designer 目前还不支持组件直接的联

我在[http://www.form-create.com/v2/guide/example.html](demo)这个里面看到有组件的层级联动，只是后端暂时不支持拖拽配置这种层级联动是吗？
