### ISSUE TITLE
一周前可以正常运行，昨天更新@form-create/element-ui之后使用一直报错

### ISSUE THREAD

**Issue by hubzhao** [xaboy/form-create-designer#39]
![image](https://user-images.githubusercontent.com/30338080/177913280-d50158de-a5be-4e22-8267-0233c5f83da9.png)

**Comment by xaboy** [comment]
暂时不要使用 vue2.7版本,  把 vue 降到2.6版本就好了
https://github.com/vuejs/core/issues/6237

**Comment by hubzhao** [comment]
好的，我试一下降低vue版本

**Comment by mlj18293180341** [comment]
老师，什么时候能升级到vue3

**Comment by xaboy** [comment]
vue3版本已发布 @mlj18293180341

**Comment by mlj18293180341** [comment]
好的👍发自我的手机-------- 原始邮件 --------发件人： xaboy ***@***.***>日期： 2022年10月23日周日 晚上7:23收件人： xaboy/form-create-designer ***@***.***>抄送： egg_vue_vuex ***@***.***>, Mention ***@***.***>主    题： Re: [xaboy/form-create-designer] ***@***.***/element-ui之后使用一直报错 (Issue #39)
Closed #39 as completed.
