### ISSUE TITLE
为什么输入框自定义校验规则，怎么填写都是提示输入有问题

### ISSUE THREAD

**Issue by YZBlankCanvas** [xaboy/form-create-designer#41]
为什么输入框自定义校验规则，怎么填写都是提示输入有问题，比如我校验数字最大值是10，我输入多少，都提示我错了

**Comment by xaboy** [comment]
怎么设置的, 截图看看. 验证类型选的是 string 吗

**Comment by YZBlankCanvas** [comment]
![1661151778(1)](https://user-images.githubusercontent.com/26454714/185859529-b19d0879-b26f-4231-9a2a-e27d31b15b83.png)
![1661151758(1)](https://user-images.githubusercontent.com/26454714/185859544-2bd0aff6-5a09-4dd2-9a92-424cc4576442.png)
我选的number类型

**Comment by YZBlankCanvas** [comment]
如果我选String类型，那就没有任何提示，好像没有进行校验一样

**Comment by xaboy** [comment]
input 的value 类型是 string 类型, 只能选 string. 输入数字建议用 inputNumber 组件

**Comment by YZBlankCanvas** [comment]
好的，感谢

**Comment by tlxiaociwei** [comment]
自定义校验规则不生效 是哪里没配置对啊
