### ISSUE TITLE
能否提供可以控制表单元素根据条件显示与否的选项

### ISSUE THREAD

**Issue by blvming** [xaboy/form-create-designer#45]
场景是，在表单中，有些组件需要显示在电脑上，有些在移动端无需要展示。大佬能否提供这样的接口，比如传入某些条件，display{ "mobile","PC"}。在组件内提供标识就可以使用form-create 来渲染。万分致谢！

**Comment by xaboy** [comment]
组件内可以通过 props.formCreateInject参数拿到相关数据
例如在 option 中定义一个 display,然后通过 formCreateInject.api.config.display 就可以拿到.
下个版本会在 formCreateInject 中增加 config 字段  @blvming

**Comment by blvming** [comment]
感谢大佬回复，我先研究下
