### ISSUE TITLE
使用vue3版本的表单设计器拖动上传组件出错

### ISSUE THREAD

**Issue by 15033556105** [xaboy/form-create-designer#48]
![1665294358750](https://user-images.githubusercontent.com/66305734/194740139-5076cb7c-92f5-49d2-81d9-1ac9e548658c.jpg)
使用vue3版本的表单设计器拖动上传组件的时候会出现这个错误

**Comment by xaboy** [comment]
更新一下 form-create 版本试试 @15033556105

**Comment by 15033556105** [comment]
form-create版本已经是最新了还是不能，而且目前还没有用到 form-create，现在只是把form-create-designer放到项目里面，别的都可以拖动，只有这个上传的组件拖动时会出现这个错误

**Comment by xaboy** [comment]
我检查一下,下个版本修复

**Comment by evannayf** [comment]
我也遇到了这个问题，只有上传组件会出错

**Comment by xaboy** [comment]
3.0.2版本已修复
