### ISSUE TITLE
vue3版本不支持按需导入element-plus吗

### ISSUE THREAD

**Issue by starSinking** [xaboy/form-create-designer#50]
vue3版本不支持按需导入element-plus组件吗
![uTools_1665543443440](https://user-images.githubusercontent.com/43055274/195239397-feb32580-2290-42a4-997b-17c3419ded78.png)

**Comment by xaboy** [comment]
```js
import formCreate from '@form-create/element-ui'
import install from '@form-create/element-ui/auto-import'
formCreate.use(install)
app.use(formCreate)
```
可以通过auto-import.js 文件一次导入所有所需依赖

**Comment by yuntian001** [comment]
> ```js
> import formCreate from '@form-create/element-ui'
> import install from '@form-create/element-ui/auto-import'
> formCreate.use(install)
> app.use(formCreate)
> ```

ts 下 import install from '@form-create/element-ui/auto-import'
报错 ，找不到@form-create/element-ui/auto-import 的类型声明

**Comment by yuntian001** [comment]
> ```js
> import formCreate from '@form-create/element-ui'
> import install from '@form-create/element-ui/auto-import'
> formCreate.use(install)
> app.use(formCreate)
> ```
> 
> 可以通过auto-import.js 文件一次导入所有所需依赖

这些警告报的是@form-create/designer 里面用到的 在 import install from '@form-create/element-ui/auto-import'里面没有这几个组件

**Comment by joker77877** [comment]
> 

按需导入无效

**Comment by joker77877** [comment]
> ```js
> import formCreate from '@form-create/element-ui'
> import install from '@form-create/element-ui/auto-import'
> formCreate.use(install)
> app.use(formCreate)
> ```
> 
> 可以通过auto-import.js 文件一次导入所有所需依赖

按需导入无效
![image](https://user-images.githubusercontent.com/62642184/210951788-16120b36-e77b-44fd-b693-230e38d34648.png)
![image](https://user-images.githubusercontent.com/62642184/210951854-16904058-200c-40a3-9cae-3af083252eaf.png)

**Comment by joker77877** [comment]
> vue3版本不支持按需导入element-plus组件吗 ![uTools_1665543443440](https://user-images.githubusercontent.com/43055274/195239397-feb32580-2290-42a4-997b-17c3419ded78.png)

请问你这个问题解决了吗。按需导入没用呢
