### ISSUE TITLE
大佬，npm引入后项目本地没问题，但是项目在构建后报错是为啥啊

### ISSUE THREAD

**Issue by starSinking** [xaboy/form-create-designer#51]
vue3版本，element-plus,vite构建
报错如下：
![image](https://user-images.githubusercontent.com/43055274/195491656-01f95be7-541a-4cac-902b-7d47a1c055b3.png)
是在构建后的这块
![image](https://user-images.githubusercontent.com/43055274/195492364-11a764ce-0964-48e2-b4e0-7e1c6a0a2e61.png)
对应的源码好像是
![image](https://user-images.githubusercontent.com/43055274/195491741-e3700637-e8b2-4cb8-aa6a-d03b40a6aab3.png)
这个位置

**Comment by starSinking** [comment]
vite构建

**Comment by starSinking** [comment]
1. 本地起来正常的的长这样：


![好的1](https://user-images.githubusercontent.com/43055274/195548027-95ec77bd-fe4e-4f0d-9897-c561ab095340.png)
![好的2](https://user-images.githubusercontent.com/43055274/195548072-ace72e7e-db9f-4d4b-859d-614a35f7eaae.png)
![好的3](https://user-images.githubusercontent.com/43055274/195548130-b7e55b51-3a93-4d67-a6e0-763643fbe9e7.png)

2. vite打包之后出问题：

![坏的1](https://user-images.githubusercontent.com/43055274/195548254-118f8667-ce31-445d-b567-be2b7eadb3d6.png)
![坏的2](https://user-images.githubusercontent.com/43055274/195548348-38834b19-5bdc-431f-8c56-abc6be943750.png)
![坏的3](https://user-images.githubusercontent.com/43055274/195548357-e25b9306-a035-4897-93fa-32aa7a460825.png)

这是vite配置的问题吗？

**Comment by xaboy** [comment]
是不是打包的时候没有把 form-create 打包进去

**Comment by starSinking** [comment]
不会吧，我在main.js中注释掉引入的designer，保留form-create，单独使用form-create的情况下打包好是正常的，引入designer就报错了。

**Comment by starSinking** [comment]
我用vite重新创建了一个干净的项目，下载好element plus以及form-create-designer后打包好还是报同样的错
![image](https://user-images.githubusercontent.com/43055274/195796873-43bf7368-e170-4241-a87c-8558b3299016.png)

![image](https://user-images.githubusercontent.com/43055274/195797105-a4f91d6d-ed8e-4bf0-8811-b354341f0a1b.png)
![image](https://user-images.githubusercontent.com/43055274/195797848-fe6ef3d6-a2da-4ad1-bd0f-63f4ca74dc13.png)

**Comment by xaboy** [comment]
<img width="569" alt="image" src="https://user-images.githubusercontent.com/21242408/195966398-71e1164a-1763-4b7d-a62c-6af2063d9c8a.png">

手动修改一下 @form-create/deisnger 包中 package.json 文件,然后重新打包试试 @starSinking 

```json
    "unpkg": "./dist/index.umd.js",
    "jsdelivr": "./dist/index.umd.js",
    "typings": "./types/index.d.ts",
    "main": "./dist/index.umd.js",
    "module": "./dist/index.es.js",
    "exports": {
        ".": {
            "import": "./dist/index.es.js",
            "require": "./dist/index.umd.js"
        }
    },
```

**Comment by starSinking** [comment]
好了，感谢

**Comment by xaboy** [comment]
好的, 下个版本修复

**Comment by xaboy** [comment]
3.0.2版本已修复
