### ISSUE TITLE
vue3版本setOption设置表单配置无效

### ISSUE THREAD

**Issue by evannayf** [xaboy/form-create-designer#52]
![image](https://user-images.githubusercontent.com/15708540/196130298-b6816664-9cc2-42eb-a260-3519fe773d38.png)

官网示例可见，导入options，点击确定后，右侧表单配置不变，没有生效

**Comment by xaboy** [comment]
感谢反馈, 我这边检查一下

**Comment by xaboy** [comment]
3.0.2版本已修复
