### ISSUE TITLE
setRule方法对于栅格布局会重复添加children

### ISSUE THREAD

**Issue by lin-code-world** [xaboy/form-create-designer#56]
![图片](https://user-images.githubusercontent.com/43373990/199948416-d3265248-0473-47fc-82c5-49367ae12471.png)

1.[{"type":"FcRow","children":[{"type":"col","props":{"span":12},"children":[{"type":"input","field":"Foii5wsnacbrh","title":"输入框","info":"","_fc_drag_tag":"input","hidden":false,"display":true}],"_fc_drag_tag":"col","hidden":false,"display":true}],"_fc_drag_tag":"row","hidden":false,"display":true}]
2.[{"type":"FcRow","children":[{"type":"col","props":{"span":12},"children":[{"type":"DragTool","props":{"dragBtn":false,"mask":false},"effect":{"_fc_tool":true},"inject":true,"on":{},"children":[{"type":"DragBox","wrap":{"show":false},"col":{"show":false},"inject":true,"props":{"rule":{"props":{"tag":"el-col","group":"default","ghostClass":"ghost","animation":150,"handle":"._fc-drag-btn","emptyInsertThreshold":0,"direction":"vertical","itemKey":"type"}},"tag":"col"},"children":[{"type":"DragTool","props":{"dragBtn":false,"mask":false},"effect":{"_fc_tool":true},"inject":true,"on":{},"children":[{"type":"DragBox","wrap":{"show":false},"col":{"show":false},"inject":true,"props":{"rule":{"props":{"tag":"el-col","group":"default","ghostClass":"ghost","animation":150,"handle":"._fc-drag-btn","emptyInsertThreshold":0,"direction":"vertical","itemKey":"type"}},"tag":"col"},"children":[{"type":"DragTool","props":{"dragBtn":true,"mask":true},"effect":{"_fc_tool":true},"inject":true,"on":{},"children":[{"type":"DragTool","props":{"dragBtn":true,"mask":true},"effect":{"_fc_tool":true},"inject":true,"on":{},"children":[{"type":"input","field":"Foii5wsnacbrh","title":"输入框","info":"","_fc_drag_tag":"input","hidden":false,"display":true,"props":{},"on":{},"options":[],"children":[],"config":{"config":{"icon":"icon-input","label":"输入框","name":"input"}},"effect":{"_fc":true}}],"options":[],"hidden":false,"display":true}],"options":[],"hidden":false,"display":true}],"on":{},"options":[],"hidden":false,"display":true}],"options":[],"hidden":false,"display":true}],"on":{},"options":[],"hidden":false,"display":true}],"options":[],"hidden":false,"display":true}],"_fc_drag_tag":"col","hidden":false,"display":true,"on":{},"options":[],"config":{"config":{"name":"col","drag":true,"dragBtn":false,"inside":true,"mask":false}},"effect":{"_fc":true}}],"_fc_drag_tag":"row","hidden":false,"display":true,"props":{},"on":{},"options":[],"config":{"config":{"icon":"icon-row","label":"栅格布局","name":"row","mask":false,"children":"col"}},"effect":{"_fc":false},"_id":"Fygc5wsnc4lti"}]

多次调用setRule方法，栅格数据结构会变的越来越复杂

**Comment by xaboy** [comment]
感谢反馈, 我这边检查一下

**Comment by xaboy** [comment]
3.1.1版本修复
