### ISSUE TITLE
按需引入方式使用报错

### ISSUE THREAD

**Issue by yuntian001** [xaboy/form-create-designer#58]
```
import formCreate from '@form-create/element-ui'
import install from '@form-create/element-ui/auto-import'
formCreate.use(install)
app.use(formCreate)

```
ts 下 import install from '@form-create/element-ui/auto-import'
报错 ，找不到@form-create/element-ui/auto-import 的类型声明

这些警告报的是@form-create/designer 里面用到的 在 import install from '@form-create/element-ui/auto-import'里面没有这几个组件

**Comment by xaboy** [comment]
感谢反馈,下个版本修复一下
