### ISSUE TITLE
大佬 啥时候支持ts呀

### ISSUE THREAD

**Issue by SoberToT** [xaboy/form-create-designer#60]

**Comment by xaboy** [comment]
你说的是那个版本, 周末更新一下就好了

**Comment by SoberToT** [comment]
> 你说的是那个版本，周末更新一下就好了

"@form-create/designer": "^1.0.8" 我装的这个版本，周末更新就能支持ts了吗

**Comment by xaboy** [comment]
可以得, vue 是那个版本

**Comment by SoberToT** [comment]
> 



> 可以得，vue 是那个版本

我现在用的vue3.2

**Comment by xaboy** [comment]
vue3需要用@form-create/designer:3.x 版本

**Comment by SoberToT** [comment]
> vue3 需要使用@form-create/designer:3.x 版本

好的 我更新一下版本然后等周末大佬更新ts支持了

**Comment by xaboy** [comment]
是用3.x 版本试试看看

**Comment by SoberToT** [comment]
> 你用3.x版考试试看

大佬牛蛙，我升级3.0版本可以了，谢谢谢
