### ISSUE TITLE
关于select组件远程搜索

### ISSUE THREAD

**Issue by chengpeng666** [xaboy/form-create-designer#62]
请问如何设置select的配置
实现远程搜索

<sub>Sent from <a href="https://apps.apple.com/cn/app/id1314212521">PPHub</a></sub>

**Comment by acelibin** [comment]
可以在右侧属性配置里找到**接口数据**配置项进行配置就可以了

**Comment by xaboy** [comment]
3.1.1版本支持配置remoteMethod

**Comment by ushirogo** [comment]
select组件可以实现带用户输入参数的搜索吗?
