### ISSUE TITLE
[bug]vue3版本使用select组件后不做任何操作，在右侧配置选择“多选”则页面崩溃

### ISSUE THREAD

**Issue by acelibin** [xaboy/form-create-designer#64]
![image](https://user-images.githubusercontent.com/12581731/212833813-506bcbda-98b6-4639-9ca3-ba954ec7a9e4.png)

下载next分支代码本地运行后的结果，但是官网示例正常，不知道是不是代码不一致的原因。

**Comment by acelibin** [comment]
![image](https://user-images.githubusercontent.com/12581731/212835800-73bb8a3f-31ce-495e-ba3f-e2b3cc7504db.png)


试了一下，master分支也是报错，但是页面还能操作

**Comment by xaboy** [comment]
3.1.1版本修复
