### ISSUE TITLE
TypeError: _vue.extend is not a function

### ISSUE THREAD

**Issue by xiaozhenxiao** [xaboy/form-create-designer#67]
```
<template>
  <div class="app-container">
    <h1 class="text-center">表单创建</h1>
    <FormDesigner ref="designer"/>
  </div>
</template>

<script setup name="formBuild">
import FormDesigner from '@form-create/designer'

</script>
```
版本：

> "@form-create/element-ui": "^3.1.18",
> "@form-create/designer": "^3.1.1",
> "vue": "3.2.37"

报错信息：
TypeError: _vue.extend is not a function
    at Function.m [as $form] (index.js:142:21)
    at index.min.js:14:81698
    at index.min.js:8:69
    at node_modules/@form-create/designer/dist/index.min.js (index.min.js:8:311)
    at __require (chunk-J43GMYXM.js?v=8659ba37:11:50)
    at dep:@form-create_designer:1:16
帮忙看下什么问题

**Comment by xaboy** [comment]
vue2版本使用form-create 2.5版本, designer 1.x版本
vue3版本使用form-create 3.1版本, designer 3.x版本 
@xiaozhenxiao

**Comment by xiaozhenxiao** [comment]
> "@form-create/element-ui": "^3.1.18",
> "@form-create/designer": "^3.1.1",
> "vue": "3.2.37"

更新了最新版，还是报这个错呢
