### ISSUE TITLE
自定义组件在规则中配置了validator，在设计器验证配置处再添加一个规则会导致validator方法消失

### ISSUE THREAD

**Issue by haoxianhuiya** [xaboy/form-create-designer#74]
版本号 @form-create/designer: 3.1.1,

UI框架的版本 element-plus 2.2.18

问题描述：自定义组件在规则中配置了validator，在拖拽表单中预览也可以生效，导出JSON也能看到相应的validator有方法。
但是如果在该组件的验证规则中点击+一条校验规则的按钮，则再看导出JSON中，validator方法就消失了。

复现： 在一个自定义组件rule中的validator配置方法，拖拽进设计表单后，在验证配置处再添加一个规则，此时再预览则validator失效。

期望：代码中配置的validator方法不因为手动配置而消失

**Comment by xaboy** [comment]
@haoxianhuiya  感谢反馈,下个版本修复

**Comment by xaboy** [comment]
3.1.2版本已修复
