### ISSUE TITLE
vue3版本中，在属性配置栏的输入框输入时，每输入一个字符就会失焦一次

### ISSUE THREAD

**Issue by XinXiaoIsMe** [xaboy/form-create-designer#79]
![image](https://user-images.githubusercontent.com/66545428/229749808-f77a4f7d-759b-4f99-bdd5-edfa7a75902d.png)

在官网的vue3示例里面发现也有同样的bug，但是vue2版本的没有。

**Comment by xaboy** [comment]
官网没有更新, 你本地用的是那个版本 @XinXiaoIsMe

**Comment by XinXiaoIsMe** [comment]
我用的3.0.2版本，但是我把源码拉下来测试也有这个问题

**Comment by XinXiaoIsMe** [comment]
@xaboy

**Comment by XinXiaoIsMe** [comment]
下载了最新版本测试还是有这个问题，不过没有每输入一次失焦一次，而是在第一次输入的时候会失焦。

**Comment by xaboy** [comment]
我这边检查一下

**Comment by xaboy** [comment]
你使用的element-ui是那个版本 @XinXiaoIsMe

**Comment by XinXiaoIsMe** [comment]
3.1.16, @xaboy

**Comment by xkrfer** [comment]
富文本组件依然每输入一个字符，失焦一次

**Comment by xaboy** [comment]
终于复现出来了, 这边正在修复

**Comment by XinXiaoIsMe** [comment]
感谢作者大大！！！



---- 回复的原邮件 ----
| 发件人 | ***@***.***> |
| 日期 | 2023年04月18日 18:10 |
| 收件人 | ***@***.***> |
| 抄送至 | ***@***.***>***@***.***> |
| 主题 | Re: [xaboy/form-create-designer] vue3版本中，在属性配置栏的输入框输入时，每输入一个字符就会失焦一次 (Issue #79) |

终于复现出来了, 这边正在修复
