### ISSUE TITLE
清空按钮失效

### ISSUE THREAD

**Issue by CrazyToMin** [xaboy/form-create-designer#83]
清空按钮无法清空设计的表单

**Comment by xaboy** [comment]
那个版本?

**Comment by CrazyToMin** [comment]
最新的版本 加载后  无法触发清空事件 但是组件自带的方法调用可以清空

**Comment by cp1001** [comment]
今天我也遇到了这个问题，项目用的element-ui@2.13，点清空无效。

原因是element-ui不同版本修改了api，如下：
<img width="747" alt="image" src="https://github.com/xaboy/form-create-designer/assets/4817619/55c1cde9-544e-4f43-8f43-c3e7be102ed4">

<img width="730" alt="image" src="https://github.com/xaboy/form-create-designer/assets/4817619/8979fed3-ed08-4d8c-bfc7-431a830bf762">


问题是：@form-create/element-ui使用了高版本的element-ui，如下图。但element-ui依赖安装在了devDependencies里，这个包应该放到dependencies，防止冲突，请@xboy。否则需要业务项目安装合适的版本，但这样就需要关注当前项目代码的兼容问题了
https://github.com/xaboy/form-create/blob/2.5/packages/element-ui/package.json
<img width="522" alt="image" src="https://github.com/xaboy/form-create-designer/assets/4817619/8d6f33a2-8fe0-4d62-8e42-8d0649ddb872">
