### ISSUE TITLE
导入json报错 json里面有自定义组件

### ISSUE THREAD

**Issue by BowenHero** [xaboy/form-create-designer#86]
![image](https://github.com/xaboy/form-create-designer/assets/35329746/a318e7f8-ee5f-4f85-a7ea-585893cd159b)

**Comment by BowenHero** [comment]
![image](https://github.com/xaboy/form-create-designer/assets/35329746/dbf12294-0842-406a-a130-d59d428108f9)
感觉生成json时就不对了 或者生成json时使用了哪些插件啊

**Comment by xaboy** [comment]
组件不支持转json,通过挂载的方式使用吧

**Comment by BowenHero** [comment]
> 

请问怎么挂载啊  我现在运用的是把您的源码下载下来直接把整个src目录下的东西直接引入到我的项目了，因为之前直接使用封装好的不适合我的需求（需要更改input和select这些组件里面的东西），所以才直接下载源码使用的。
