### ISSUE TITLE
vu3+vite使用formCreate 一直报错

### ISSUE THREAD

**Issue by xiaoBai516** [xaboy/form-create-designer#88]
不管是业务里引入import formCreate from '@form-create/element-ui'还是main.js 注册，都一直报这个Failed to resolve component: form-creat
If this is a native custom element, make sure to exclude it from component resolution via compilerOptions.isCustomElement. 
`
<template>
  <form-create
    v-model="fapi"
    :rule="rule"
    :option="option"
    @submit="onSubmit"
  ></form-create>
</template>
<script name="JsonDrawer" setup>
import formCreate from "@form-create/element-ui";
let detailForm = ref({
  rule: [],
  option: {},
  val: {}
})
const onSubmit = formData => {
  console.log(data, '===')
}
const getFormInfos = () => {
  //FcDesigner 生成的`JSON`
  const FcDesignerRule =
    '[{"type":"input","field":"cuk5qqdw3umc","title":"输入框","info":"","_fc_drag_tag":"input","hidden":false,"display":true}]'
  //FcDesigner 生成的`options`
  const FcDesignerOptions =
    '{"form":{"labelPosition":"right","size":"mini","labelWidth":"125px","hideRequiredAsterisk":false,"showMessage":true,"inlineMessage":false}}'
  detailForm.value.rule = formCreate.parseJson(FcDesignerRule)
  detailForm.value.option = formCreate.parseJson(FcDesignerOptions)
}
<script>
`

**Comment by xaboy** [comment]
mian.ts
```js
import formCreate from "@form-create/element-ui";
const app = createApp(App);
app.use(formCreate)
```

组件中
```vue
<script setup lang="ts">
import fc from "@form-create/element-ui";
import {ref} from "vue";

let detailForm = ref({rule: [], option: {}, val: {}})
const onSubmit = formData => {
    console.log(formData, '===')
}
const getFormInfos = () => {
    const FcDesignerRule = '[{"type":"input","field":"cuk5qqdw3umc","title":"输入框","info":"","_fc_drag_tag":"input","hidden":false,"display":true}]'
    const FcDesignerOptions = '{"form":{"labelPosition":"right","size":"mini","labelWidth":"125px","hideRequiredAsterisk":false,"showMessage":true,"inlineMessage":false}}'
    detailForm.value.rule = fc.parseJson(FcDesignerRule)
    detailForm.value.option = fc.parseJson(FcDesignerOptions)
}
getFormInfos()
</script>

<template>
    <form-create :rule="detailForm.rule" @submit="onSubmit"></form-create>
</template>
```

组件中导入formCreate时定义为`fc`是为了避免冲突
在组件中挂载formCreate是的写法
```js
import fc from "@form-create/element-ui";
const formCreate = fc.$form();
```

**Comment by Qwqw127** [comment]
同问

**Comment by Qwqw127** [comment]
> 

"vue": "^3.2.13",
 "@form-create/designer": "^3.1.3",

**Comment by xaboy** [comment]
3.1.5版本已修复 @Qwqw127
