### ISSUE TITLE
FcDesigner回显报错

### ISSUE THREAD

**Issue by yww0807** [xaboy/form-create-designer#89]
回显的时候 designer.setOption() 方法 报错
报错信息： Cannot set properties of undefined (setting 'formCreateSubmitBtn')

**Comment by xaboy** [comment]
更新到最新版本试试,如果还有问题请发一下规则

**Comment by NJHSFNAK** [comment]
> 更新到最新版本试试,如果还有问题请发一下规则

#113更新到最新版问题还是存在；JSON数据结构如下

**Comment by NJHSFNAK** [comment]
> 更新到最新版本试试,如果还有问题请发一下规则

作者您好，更新到最新版还是有问题，问题可以查看#113，option的JSON数据如下

**Comment by NJHSFNAK** [comment]
> 更新到最新版本试试,如果还有问题请发一下规则

作者您好，更新到最新版还是有问题，问题可以查看https://github.com/xaboy/form-create-designer/issues/113，option的JSON数据如下

**Comment by NJHSFNAK** [comment]
> 更新到最新版本试试,如果还有问题请发一下规则

作者您好，更新到最新版还是有问题，问题可以查看https://github.com/xaboy/form-create-designer/issues/113，option的JSON数据如下 {"form":{"labelPosition":"left","size":"default","labelWidth":"125px","hideRequiredAsterisk":false,"showMessage":true,"inlineMessage":false},"submitBtn":{"show":true,"innerText":"提交"},"resetBtn":{"show":false,"innerText":"重置"}}

**Comment by xaboy** [comment]
有没有报错? 这边还是没有复现 @NJHSFNAK 
```
vm.setOption({"form":{"labelPosition":"left","size":"default","labelWidth":"125px","hideRequiredAsterisk":false,"showMessage":true,"inlineMessage":false},"submitBtn":{"show":true,"innerText":"提交"},"resetBtn":{"show":false,"innerText":"重置"}})
```

**Comment by NJHSFNAK** [comment]
> 有没有报错? 这边还是没有复现 @NJHSFNAK
> 
> ```
> vm.setOption({"form":{"labelPosition":"left","size":"default","labelWidth":"125px","hideRequiredAsterisk":false,"showMessage":true,"inlineMessage":false},"submitBtn":{"show":true,"innerText":"提交"},"resetBtn":{"show":false,"innerText":"重置"}})
> ```

作者您好，我看#14解决了问题，使用setOption时传入的字符串，传入对象就可以显示了。
