### ISSUE TITLE
vue3版本全局引入出错

### ISSUE THREAD

**Issue by adou2236** [xaboy/form-create-designer#92]
使用window.formCreate.create()引入出现这种情况
![image](https://github.com/xaboy/form-create-designer/assets/57088340/58df2a15-a285-470f-b50d-ca4dd3aa1862)

**Comment by xaboy** [comment]
element-plus需要自己导入,并全局挂载,然后在vue组件的mounted中通过 this.$formCreate.create方法生成

**Comment by adou2236** [comment]
> element-plus需要自己导入,并全局挂载,然后在vue组件的mounted中通过 this.$formCreate.create方法生成

如果不在vue文件中使用该怎么做呢

**Comment by xaboy** [comment]
```html

<div id="app">
 
  </div>
```
```js
const app = Vue.createApp({
    mounted(){
        this.$formCreate([])
    }
});
app.use(ElementPlus).use(formCreate).mount('#app');
```
