### ISSUE TITLE
多行文本框

### ISSUE THREAD

**Issue by mizhexiaoxiao** [xaboy/form-create-designer#93]
目前没有看到多行文本框，是用富文本框替代了吗？想知道是出于什么考虑，感觉普通文本框也是挺常用的

**Comment by xaboy** [comment]
<img width="1627" alt="image" src="https://github.com/xaboy/form-create-designer/assets/21242408/36377150-1bd0-40d2-be76-cd971a1b9e57">
这个当前有的 @mizhexiaoxiao

**Comment by mizhexiaoxiao** [comment]
> <img alt="image" width="1627" src="https://user-images.githubusercontent.com/21242408/261937601-36377150-1bd0-40d2-be76-cd971a1b9e57.png"> 这个当前有的 @mizhexiaoxiao

原来如此，谢谢。
