### ISSUE TITLE
VUE3 + TS + VITE 项目打包提示 eval

### ISSUE THREAD

**Issue by a2734961** [xaboy/form-create-designer#94]
node_modules/@form-create/designer/dist/index.min.js (8:6144) Use of eval in "node_modules/@form-create/designer/dist/index.min.js" is strongly discouraged as it poses security risks and may cause issues with minification.
node_modules/@form-create/designer/dist/index.min.js (14:300562) Use of eval in "node_modules/@form-create/designer/dist/index.min.js" is strongly discouraged as it poses security risks and may cause issues with minification.
node_modules/@form-create/designer/dist/index.min.js (14:303923) Use of eval in "node_modules/@form-create/designer/dist/index.min.js" is strongly discouraged as it poses security risks and may cause issues with minification.

版本："@form-create/designer": "1.0.10"

可以不使用eval吗

**Comment by xaboy** [comment]
下个版本修复

**Comment by BrotherJie** [comment]
我用的node v18.16.0, vite 4.5.0， @form--create/designer 3.1.4，打包时候还是出现上面的问题

**Comment by xaboy** [comment]
@BrotherJie 把designer和form-create都更新到最新版本就好了

**Comment by BrotherJie** [comment]
我用pnpm装的，pnpm-lock.yaml里面看到
/@form-create/designer@3.14(vue@3.3.7)
/@form-create/element-ui@3.1.25(vue@3.3.7)

这两个难道不是最新的吗？我是用vite --mode pro方式打包的

**Comment by xaboy** [comment]
我检查了下,`@form-create/designer@3.14`包里面确实存在`eval`方法,我在下个版本修复一下

**Comment by jiiiiiie** [comment]
大佬什么时候发布下一版本修复这个问题啊？

**Comment by xaboy** [comment]
3.1.5版本已修复 @jiiiiiie  @BrotherJie
